### ISSUE TITLE
Create an account

### ISSUE THREAD

**Issue by BullenBiss** [Maggemkay/Aristotle-Phone#22]
As a user 
I want to be able to create an account
so that I can login to the app.

**Comment by zaiiss** [comment]
- [x] Background color and orange/pink symbol

- [x] Text Aristotle

- [x] 6 text field with correct name

- [x]  Sign up button

- [x] Cancel button

**Comment by Maggemkay** [comment]
- [x] Check database

- [x] Handle repsonse

- [x] Handle input validation (Back-end)

- [x] Handle input validation (Front-end)
