### ISSUE TITLE
Change email [wont do]

### ISSUE THREAD

**Issue by BullenBiss** [Maggemkay/Aristotle-Phone#53]
As a user I want to be able to change my profile email. _Given that I am logged in and can view my profile, I want to change my profile email_

**Comment by Maggemkay** [comment]
- [ ] Check database

- [ ] Handle repsonse

- [ ] Send to the database (create new entity)

- [ ] Handle input validation

**Comment by zaiiss** [comment]
We wont do this - username/mail should not be changed.
