### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by zaiiss** [Maggemkay/Aristotle-Phone#55]
As a user 
I want to be able to login 
so that I can use the app.

**Comment by zaiiss** [comment]
- [ ] nbkabkab

**Comment by zaiiss** [comment]
- [x] Background color and orange/pink symbol

- [x] Text Aristotle


- [x] Text field for username

- [x] Text field for password

- [x] Text - forgot your password?

- [x] Text - don't have an account?

- [x] Log in button

- [x] Forgot password view

- [x] Reset password view 1

- [x] Reset password view 2

- [ ] Handle wrong username and password - popup

**Comment by Maggemkay** [comment]
- [x] Check database

- [x] Handle repsonse

- [x] Save JWT token
