### ISSUE TITLE
top navigation bar 

### ISSUE THREAD

**Issue by jing224** [Maggemkay/Aristotle-Phone#57]
As user, i want to see the notification and profile on the top

**Comment by Maggemkay** [comment]
- [ ] Task 1

- [ ] Task 2

- [ ] Task 3

**Comment by Maggemkay** [comment]
- [ ] Connect fragment id to top bar text field

- [ ] Go back to previous fragment

- [ ] Add color

- [ ]  Add profile picture

- [ ]  Add notification symbol

- [ ] Go to profile
